using Signal9.Shared.DTOs.Common;
using Signal9.Shared.Models;

namespace Signal9.Shared.DTOs;

/// <summary>
/// Extension methods for DTO conversions in the unified hierarchy architecture
/// </summary>
public static class DtoExtensions
{
    /// <summary>
    /// Convert AgentRegistrationRequest to AgentDto
    /// </summary>
    public static AgentDto ToAgentDto(this AgentRegistrationRequest request)
    {
        return new AgentDto
        {
            // Id is auto-generated by BaseDto<Guid>
            ParentId = request.ParentId ?? Guid.Empty,  // Fixed: handle nullable Guid properly
            MachineName = request.MachineName,
            Domain = request.Domain,
            OperatingSystem = request.OperatingSystem,
            OSVersion = request.OSVersion,
            Architecture = request.Architecture ?? "Unknown",
            TotalMemoryMB = request.TotalMemoryMB,
            ProcessorCores = request.ProcessorCores,
            ProcessorName = request.ProcessorName,
            IpAddress = request.IpAddress ?? "Unknown",
            MacAddress = request.MacAddress,
            FirstSeen = DateTime.UtcNow,
            LastSeen = request.LastSeen,
            Status = request.IsOnline ? AgentStatus.Online : AgentStatus.Offline,
            Version = request.Version,
            Tags = null // Can be updated later through update operations
        };
    }

    /// <summary>
    /// Create AgentResponse from AgentDto
    /// </summary>
    public static AgentResponse CreateAgentResponse(this AgentDto agentDto, string? tenantName = null, string? groupName = null)
    {
        return AgentResponse.FromAgentDto(agentDto, tenantName, groupName);
    }
}

/// <summary>
/// Agent Registration Response DTO
/// </summary>
public record AgentRegistrationResponse
{
    /// <summary>
    /// Parent ID (tenant) that the agent was registered under
    /// </summary>
    public Guid? ParentId { get; init; }
    
    /// <summary>
    /// The registered agent response
    /// </summary>
    public AgentResponse? Agent { get; init; }
    
    /// <summary>
    /// Configuration data for the agent
    /// </summary>
    public object? Configuration { get; init; }
    
    /// <summary>
    /// Registration status message
    /// </summary>
    public string? RegistrationStatus { get; init; }
    
    /// <summary>
    /// Additional message
    /// </summary>
    public string? Message { get; init; }
}